services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    restart: always
    container_name: open-webui
    hostname: ia
    volumes:
      - open-webui:/app/backend/data
      - ollama:/root/.ollama
volumes:
  open-webui:
  ollama: