include:
  # Servi√ßos
  # - ./GitLab/docker-compose.yml
  - ./Nextcloud/docker-compose.yml
  - ./Wordpress/docker-compose.yml
  - ./Mastodon/docker-compose.yml

  # Infraestrutura
  - ./ProxyHttp/docker-compose.yml
  - ./ServidorDnsAutoritativo/docker-compose.yml