include:
  # Servi√ßos
  # - ./GitLab/docker-compose.yml
  - ./Nextcloud/docker-compose.yml
  - ./Wordpress/docker-compose.yml
  - ./Mastodon/docker-compose.yml
  - ./IA/docker-compose.yml

  # Infraestrutura
  - ./ProxyHttp/docker-compose.yml
  - ./CoreDNS/docker-compose.yml
  - ./Unbound/docker-compose.yml

networks:
  dns-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.254.0.0/24
  default: