services:
  dockpeek:
    image: dockpeek/dockpeek:latest
    container_name: dockpeek
    environment:
      - SECRET_KEY=${DOCKPEEK_SECRET_KEY}
      - USERNAME=${DOCKPEEK_USERNAME}
      - PASSWORD=${DOCKPEEK_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always