services:
  gitlab:
    image: gitlab/gitlab-ce
    container_name: GitLab
    restart: always
    hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${GITLAB_HOSTNAME}'
        gitlab_rails['lfs_enabled'] = true
        puma['worker_processes'] = 2
        sidekiq['concurrency'] = 9
        prometheus_monitoring['enable'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 8022
    ports:
      # - '80:80'
      # - '443:443'
      - 8022:8022
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'