services:
  wordpress:
    image: wordpress
    hostname: ${WORDPRESS_HOSTNAME}
    restart: always
    # ports:
    #   - "80:80"
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ~/Wordpress/app:/var/www/html
  wordpress_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ~/Wordpress/db:/var/lib/mysql

volumes:
  wordpress:
  wordpress_db: